#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpp_gis.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_ENG_GTRACK_KPP")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_T_LOG_DATA(TBL_T_LOG_DATA instance);
    partial void UpdateTBL_T_LOG_DATA(TBL_T_LOG_DATA instance);
    partial void DeleteTBL_T_LOG_DATA(TBL_T_LOG_DATA instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_ENG_GTRACK_KPPConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_T_LOG_DATA> TBL_T_LOG_DATAs
		{
			get
			{
				return this.GetTable<TBL_T_LOG_DATA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_T_LOG_DATA")]
	public partial class TBL_T_LOG_DATA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_PositionLogID;
		
		private string _FK_UnitID;
		
		private string _Plate_No;
		
		private System.Nullable<System.DateTime> _PositionDateTime;
		
		private System.Nullable<System.DateTime> _GPSDateTime;
		
		private System.Nullable<double> _Longitude;
		
		private System.Nullable<double> _Latitude;
		
		private System.Nullable<int> _Speed;
		
		private System.Nullable<int> _Direction;
		
		private System.Nullable<int> _Altitude;
		
		private System.Nullable<int> _NumberOfSatelite;
		
		private System.Nullable<int> _ReportID;
		
		private System.Nullable<int> _Mileage;
		
		private string _AccState;
		
		private string _InputValue;
		
		private string _OutputValue;
		
		private string _AnalogInput9;
		
		private string _AnalogInput10;
		
		private string _LastRFID;
		
		private string _Location;
		
		private System.Nullable<System.DateTime> _Insert_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_PositionLogIDChanging(int value);
    partial void OnPK_PositionLogIDChanged();
    partial void OnFK_UnitIDChanging(string value);
    partial void OnFK_UnitIDChanged();
    partial void OnPlate_NoChanging(string value);
    partial void OnPlate_NoChanged();
    partial void OnPositionDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnPositionDateTimeChanged();
    partial void OnGPSDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnGPSDateTimeChanged();
    partial void OnLongitudeChanging(System.Nullable<double> value);
    partial void OnLongitudeChanged();
    partial void OnLatitudeChanging(System.Nullable<double> value);
    partial void OnLatitudeChanged();
    partial void OnSpeedChanging(System.Nullable<int> value);
    partial void OnSpeedChanged();
    partial void OnDirectionChanging(System.Nullable<int> value);
    partial void OnDirectionChanged();
    partial void OnAltitudeChanging(System.Nullable<int> value);
    partial void OnAltitudeChanged();
    partial void OnNumberOfSateliteChanging(System.Nullable<int> value);
    partial void OnNumberOfSateliteChanged();
    partial void OnReportIDChanging(System.Nullable<int> value);
    partial void OnReportIDChanged();
    partial void OnMileageChanging(System.Nullable<int> value);
    partial void OnMileageChanged();
    partial void OnAccStateChanging(string value);
    partial void OnAccStateChanged();
    partial void OnInputValueChanging(string value);
    partial void OnInputValueChanged();
    partial void OnOutputValueChanging(string value);
    partial void OnOutputValueChanged();
    partial void OnAnalogInput9Changing(string value);
    partial void OnAnalogInput9Changed();
    partial void OnAnalogInput10Changing(string value);
    partial void OnAnalogInput10Changed();
    partial void OnLastRFIDChanging(string value);
    partial void OnLastRFIDChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnInsert_dateChanging(System.Nullable<System.DateTime> value);
    partial void OnInsert_dateChanged();
    #endregion
		
		public TBL_T_LOG_DATA()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_PositionLogID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PK_PositionLogID
		{
			get
			{
				return this._PK_PositionLogID;
			}
			set
			{
				if ((this._PK_PositionLogID != value))
				{
					this.OnPK_PositionLogIDChanging(value);
					this.SendPropertyChanging();
					this._PK_PositionLogID = value;
					this.SendPropertyChanged("PK_PositionLogID");
					this.OnPK_PositionLogIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_UnitID", DbType="VarChar(50)")]
		public string FK_UnitID
		{
			get
			{
				return this._FK_UnitID;
			}
			set
			{
				if ((this._FK_UnitID != value))
				{
					this.OnFK_UnitIDChanging(value);
					this.SendPropertyChanging();
					this._FK_UnitID = value;
					this.SendPropertyChanged("FK_UnitID");
					this.OnFK_UnitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Plate_No", DbType="VarChar(50)")]
		public string Plate_No
		{
			get
			{
				return this._Plate_No;
			}
			set
			{
				if ((this._Plate_No != value))
				{
					this.OnPlate_NoChanging(value);
					this.SendPropertyChanging();
					this._Plate_No = value;
					this.SendPropertyChanged("Plate_No");
					this.OnPlate_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PositionDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> PositionDateTime
		{
			get
			{
				return this._PositionDateTime;
			}
			set
			{
				if ((this._PositionDateTime != value))
				{
					this.OnPositionDateTimeChanging(value);
					this.SendPropertyChanging();
					this._PositionDateTime = value;
					this.SendPropertyChanged("PositionDateTime");
					this.OnPositionDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GPSDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GPSDateTime
		{
			get
			{
				return this._GPSDateTime;
			}
			set
			{
				if ((this._GPSDateTime != value))
				{
					this.OnGPSDateTimeChanging(value);
					this.SendPropertyChanging();
					this._GPSDateTime = value;
					this.SendPropertyChanged("GPSDateTime");
					this.OnGPSDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float")]
		public System.Nullable<double> Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float")]
		public System.Nullable<double> Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Speed", DbType="Int")]
		public System.Nullable<int> Speed
		{
			get
			{
				return this._Speed;
			}
			set
			{
				if ((this._Speed != value))
				{
					this.OnSpeedChanging(value);
					this.SendPropertyChanging();
					this._Speed = value;
					this.SendPropertyChanged("Speed");
					this.OnSpeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direction", DbType="Int")]
		public System.Nullable<int> Direction
		{
			get
			{
				return this._Direction;
			}
			set
			{
				if ((this._Direction != value))
				{
					this.OnDirectionChanging(value);
					this.SendPropertyChanging();
					this._Direction = value;
					this.SendPropertyChanged("Direction");
					this.OnDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Altitude", DbType="Int")]
		public System.Nullable<int> Altitude
		{
			get
			{
				return this._Altitude;
			}
			set
			{
				if ((this._Altitude != value))
				{
					this.OnAltitudeChanging(value);
					this.SendPropertyChanging();
					this._Altitude = value;
					this.SendPropertyChanged("Altitude");
					this.OnAltitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfSatelite", DbType="Int")]
		public System.Nullable<int> NumberOfSatelite
		{
			get
			{
				return this._NumberOfSatelite;
			}
			set
			{
				if ((this._NumberOfSatelite != value))
				{
					this.OnNumberOfSateliteChanging(value);
					this.SendPropertyChanging();
					this._NumberOfSatelite = value;
					this.SendPropertyChanged("NumberOfSatelite");
					this.OnNumberOfSateliteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReportID", DbType="Int")]
		public System.Nullable<int> ReportID
		{
			get
			{
				return this._ReportID;
			}
			set
			{
				if ((this._ReportID != value))
				{
					this.OnReportIDChanging(value);
					this.SendPropertyChanging();
					this._ReportID = value;
					this.SendPropertyChanged("ReportID");
					this.OnReportIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mileage", DbType="Int")]
		public System.Nullable<int> Mileage
		{
			get
			{
				return this._Mileage;
			}
			set
			{
				if ((this._Mileage != value))
				{
					this.OnMileageChanging(value);
					this.SendPropertyChanging();
					this._Mileage = value;
					this.SendPropertyChanged("Mileage");
					this.OnMileageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccState", DbType="VarChar(10)")]
		public string AccState
		{
			get
			{
				return this._AccState;
			}
			set
			{
				if ((this._AccState != value))
				{
					this.OnAccStateChanging(value);
					this.SendPropertyChanging();
					this._AccState = value;
					this.SendPropertyChanged("AccState");
					this.OnAccStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InputValue", DbType="VarChar(50)")]
		public string InputValue
		{
			get
			{
				return this._InputValue;
			}
			set
			{
				if ((this._InputValue != value))
				{
					this.OnInputValueChanging(value);
					this.SendPropertyChanging();
					this._InputValue = value;
					this.SendPropertyChanged("InputValue");
					this.OnInputValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutputValue", DbType="VarChar(50)")]
		public string OutputValue
		{
			get
			{
				return this._OutputValue;
			}
			set
			{
				if ((this._OutputValue != value))
				{
					this.OnOutputValueChanging(value);
					this.SendPropertyChanging();
					this._OutputValue = value;
					this.SendPropertyChanged("OutputValue");
					this.OnOutputValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalogInput9", DbType="VarChar(50)")]
		public string AnalogInput9
		{
			get
			{
				return this._AnalogInput9;
			}
			set
			{
				if ((this._AnalogInput9 != value))
				{
					this.OnAnalogInput9Changing(value);
					this.SendPropertyChanging();
					this._AnalogInput9 = value;
					this.SendPropertyChanged("AnalogInput9");
					this.OnAnalogInput9Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalogInput10", DbType="VarChar(50)")]
		public string AnalogInput10
		{
			get
			{
				return this._AnalogInput10;
			}
			set
			{
				if ((this._AnalogInput10 != value))
				{
					this.OnAnalogInput10Changing(value);
					this.SendPropertyChanging();
					this._AnalogInput10 = value;
					this.SendPropertyChanged("AnalogInput10");
					this.OnAnalogInput10Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastRFID", DbType="VarChar(50)")]
		public string LastRFID
		{
			get
			{
				return this._LastRFID;
			}
			set
			{
				if ((this._LastRFID != value))
				{
					this.OnLastRFIDChanging(value);
					this.SendPropertyChanging();
					this._LastRFID = value;
					this.SendPropertyChanged("LastRFID");
					this.OnLastRFIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(500)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Insert_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Insert_date
		{
			get
			{
				return this._Insert_date;
			}
			set
			{
				if ((this._Insert_date != value))
				{
					this.OnInsert_dateChanging(value);
					this.SendPropertyChanging();
					this._Insert_date = value;
					this.SendPropertyChanged("Insert_date");
					this.OnInsert_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
